### ISSUE TITLE
PHPStorm reporting install plugin from disk Error

### ISSUE THREAD

**Issue by ghost** [brideo/phpstorm-live-templates-magento-2#4]
Hi Brideo,

I am receiving the following error:

Fail to load plugin descriptor from file live-template.jar

Any idea?
![screenshots](https://cloud.githubusercontent.com/assets/4475032/23743277/eafb951c-04a7-11e7-90e3-fbcc90944086.png)

**Comment by brideo** [comment]
hmm weird, I will try re-exporting and uploading again shortly.

**Comment by ghost** [comment]
Thanks

**Comment by versdivers** [comment]
I have the same issue

**Comment by brideo** [comment]
Hey guys,

I have uploaded a new one.

What version of PHP Storm are you running?

**Comment by versdivers** [comment]
I am running PHP storm 2016.2.2

With the new fille i still get 'failed to load descriptor'

Edit : After upgrading to 3.3 (latest download) i still have 'fail to load plugin descriptor from live-templates.jar'

**Comment by versdivers** [comment]
I have now implemented them manually by copy/pasting everything. Also i added a registration.php (since that is needed now)

**Comment by versdivers** [comment]
I am not sure how this pull request thing here works (new to coding with github) but the code for the registration.php : 

mregistration --> Registration of the module

Template text:

```
<?php
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    '$Namespace_Modulename$',
    __DIR__
);
```

edit: fixed the old one.

**Comment by ghost** [comment]
Works if you import using import settings.

Thanks again brideo

**Comment by brideo** [comment]
Hey @versdivers,

You can fork the repository and then create a pull request in :)
